---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-c5c89a2371d4085d0991badefaf1f0e9
  name: sock-shop
  namespace: wego-system
spec:
  branch: master
  config_url: ssh://git@github.com/sympatheticmoose/new-gitops.git
  deployment_type: kustomize
  path: ./deploy/kubernetes/manifests
  source_type: git
  url: ssh://git@github.com/sympatheticmoose/microservices-demo.git
